import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { Result } from '../types';

export function generateScorecardPDF(result: Result) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const studentName = result.attempt.student?.name || 'Student';
  const rollNumber = result.attempt.student?.rollNumber || 'N/A';
  const examName = result.attempt.exam?.name || 'Examination';
  const score = result.score;
  const percentage = result.percentage ? result.percentage.toFixed(1) : '0';
  const totalQuestions = result.attempt.exam?.totalQuestions || 0;
  const passingPercentage = result.attempt.exam?.passingPercentage || 50;
  const isPassed = result.isPassed;
  const examDate = new Date(result.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const violationCount = result.violationCount;
  
  // Format Time Taken (e.g. 15m 30s)
  const timeSeconds = result.timeTaken;
  const minutes = Math.floor(timeSeconds / 60);
  const seconds = timeSeconds % 60;
  const durationStr = `${minutes}m ${seconds}s`;

  // Draw Page border
  doc.setDrawColor(99, 102, 241); // Primary indigo
  doc.setLineWidth(1.5);
  doc.rect(5, 5, 200, 287);

  doc.setDrawColor(229, 231, 235); // Light grey inner border
  doc.setLineWidth(0.5);
  doc.rect(7, 7, 196, 283);

  // Header Banner (Dark Theme Accent)
  doc.setFillColor(19, 19, 26); // Card background color
  doc.rect(8, 8, 194, 40, 'F');

  // Title Logo Text
  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('SECUREPARIKSHA', 15, 25);

  doc.setTextColor(99, 102, 241); // Indigo color
  doc.setFontSize(10);
  doc.text('SECURE ONLINE EXAMINATION & AI PROCTORING PLATFORM', 15, 31);

  // Verified Badge Stamp
  doc.setFillColor(99, 102, 241);
  doc.rect(155, 15, 40, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('Helvetica', 'bold');
  doc.text('AI VERIFIED REPORT', 160, 21);

  // Document Title
  doc.setTextColor(31, 41, 55);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('OFFICIAL EXAM SCORECARD', 105, 65, { align: 'center' });

  // Divider Line
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.8);
  doc.line(40, 72, 170, 72);

  // Candidate Details Title
  doc.setFontSize(12);
  doc.setTextColor(55, 65, 81);
  doc.text('CANDIDATE INFORMATION', 15, 85);

  // Student details table
  (doc as any).autoTable({
    startY: 88,
    margin: { left: 15, right: 15 },
    theme: 'plain',
    body: [
      ['Student Name:', studentName, 'Roll Number:', rollNumber],
      ['Date of Exam:', examDate, 'Email Address:', result.attempt.student?.userId ? 'Verified' : 'N/A'],
    ],
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', width: 35 },
      1: { width: 60 },
      2: { fontStyle: 'bold', width: 35 },
      3: { width: 60 },
    },
  });

  // Exam Details Title
  doc.text('EXAMINATION SUMMARY', 15, 115);

  // Score Table
  (doc as any).autoTable({
    startY: 118,
    margin: { left: 15, right: 15 },
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241], halign: 'center' },
    bodyStyles: { halign: 'center' },
    head: [['Parameter', 'Value Details']],
    body: [
      ['Exam Title', examName],
      ['Total Attempted Questions', `${totalQuestions} MCQs`],
      ['Total Score Earned', `${score} Marks`],
      ['Achieved Percentage', `${percentage}%`],
      ['Passing Threshold', `${passingPercentage}%`],
      ['Time Duration Spent', durationStr],
      ['Proctoring Warning Violations', `${violationCount} incidents`],
    ],
  });

  // Result Banner box (Pass / Fail indicator)
  const currentY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFillColor(isPassed ? 16 : 239, isPassed ? 185 : 68, isPassed ? 129 : 68); // green or red
  doc.rect(15, currentY, 180, 20, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  const statusStr = isPassed ? 'RESULT STATUS: PASSED' : 'RESULT STATUS: FAILED';
  doc.text(statusStr, 105, currentY + 12, { align: 'center' });

  // Security Verification footprint
  const footerY = currentY + 35;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128); // Grey
  doc.setFont('Helvetica', 'normal');
  doc.text('Verification Code Stamp:', 15, footerY);
  doc.setFont('Courier', 'normal');
  const secureHash = btoa(`${studentName}:${examName}:${score}:${percentage}:${violationCount}`).substring(0, 32);
  doc.text(secureHash, 15, footerY + 4);

  doc.setFont('Helvetica', 'normal');
  doc.text('* This document is digitally generated by SecurePariksha under real-time WebRTC and AI eye-gaze tracking.', 15, footerY + 12);
  doc.text('Any tampering or replication of this certificate voids the score validation.', 15, footerY + 16);

  // Draw Signatures
  doc.line(145, footerY + 4, 190, footerY + 4);
  doc.text('Authorized Administrator', 150, footerY + 8);

  // Save the PDF
  doc.save(`SecurePariksha_Scorecard_${rollNumber}.pdf`);
}
